CREATE SCHEMA `ftt` ;

CREATE TABLE `USER` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(250) DEFAULT NULL,
    `EMAIL` VARCHAR(250) DEFAULT NULL,
    `COLOR` VARCHAR(20) DEFAULT NULL,
    PRIMARY KEY (`ID`)
)  ENGINE=INNODB AUTO_INCREMENT=9 DEFAULT CHARSET=UTF8MB4 COLLATE = UTF8MB4_0900_AI_CI;

CREATE TABLE `PASSWORD` (
	`ID` INT NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(200) DEFAULT NULL,
    `EMAIL` VARCHAR(200) DEFAULT NULL,
    `PASSWORD` VARCHAR(100) DEFAULT NULL,
    `SITE` VARCHAR(100) DEFAULT NULL,
    PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=9 DEFAULT CHARSET=UTF8MB4 COLLATE = UTF8MB4_0900_AI_CI;

CREATE TABLE `REMEMBER` (
	`ID` INT NOT NULL AUTO_INCREMENT,
    `QUESTION` VARCHAR(200) DEFAULT NULL,
    `ANSWER` VARCHAR(200) DEFAULT NULL,
    `SITE` VARCHAR(100) DEFAULT NULL,
    PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=9 DEFAULT CHARSET=UTF8MB4 COLLATE = UTF8MB4_0900_AI_CI;


